version: "3.9"

volumes:
  postgres_data:
  redisdata: {}

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ".env"

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
